version: '3.4'

services:

    cafy:
        build:
            context: ./myCafySvc
            dockerfile: dockerfile
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        #restart: always
        environment:    
            - PUID=1000
            - PGID=1000
        #command: 
        ports:
            - 8080:8080
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - cafy-data:/usr/app/node-ecam-coffee
            - cafy-logs:/root/.npm/_logs
        devices:
            # Could be different, check your host
            #sudo ls -l /sys/class/bluetooth
            #sudo hcitool dev
            - "/dev/ttyAMA0:/dev/ttyAMA0"   
        network_mode: "host"
        cap_add:
            - NET_ADMIN
    
 volumes:
    cafy-data:
    cafy-logs:
    
#networks